@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

POST http://{{host}}/envelopes
Content-Type:{{contentType}}

{
  "budget": 4500,
  "title": "Budget 5"
}

###

GET http://{{host}}/envelopes

###

GET http://{{host}}/envelopes/3

###

PUT http://{{host}}/envelopes/2
Content-Type:{{contentType}}

{
  "budget": 5000,
  "title": "Budget 2"
}

###

DELETE http://{{host}}/envelopes/6

###

POST http://{{host}}/envelopes/transfer/1/2
Content-Type:{{contentType}}

{
  "value": 100
}

###

POST http://{{host}}/transactions
Content-Type:{{contentType}}

{
  "date": "2023-01-15",
  "amount": "500",
  "recipient": "Nero",
  "envelopeId": 2
}